### ISSUE TITLE
Unknown column 'store_ids' in 'where clause'

### ISSUE THREAD

**Issue by ferret-e** [mageplaza/magento-2-blog#104]
Installing latest version (2.5) any product page shows following error in developer mode:
```2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_ids' in 'where clause', query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id=50 WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2017-11-22 19:00:17')
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_ids' in 'where clause'

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_ids' in 'where clause', query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id=50 WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2017-11-22 19:00:17')
#0 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT COUNT(*)...', Array)
#6 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Data/Collection/AbstractDb.php(220): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(131): Magento\Framework\Data\Collection\AbstractDb->getSize()
#9 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(76): Mageplaza\Blog\Block\Post\Relatedpost->setTabTitle()
#10 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Mageplaza\Blog\Block\Post\Relatedpost->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Registry), Object(Mageplaza\Blog\Helper\Data), Array)
#11 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mageplaza\\Blog\\...', Array)
#12 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Blog\\...', Array)
#13 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Mageplaza\\Blog\\...', Array)
#14 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Mageplaza\\Blog\\...', Array)
#15 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Mageplaza\\Blog\\...', Array)
#16 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('Mageplaza\\Blog\\...', 'related.post.ta...', Array)
#17 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'related.post.ta...')
#18 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#19 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#21 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#22 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#23 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#24 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#25 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#26 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#27 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#28 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-cms/Controller/Noroute/Index.php(44): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Noroute\Index\Interceptor), 'no-route-2')
#29 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(24): Magento\Cms\Controller\Noroute\Index->execute()
#30 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Action/Action.php(107): Magento\Cms\Controller\Noroute\Index\Interceptor->execute()
#31 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#32 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Noroute\Index\Interceptor->___callParent('dispatch', Array)
#33 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Noroute\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(39): Magento\Cms\Controller\Noroute\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#35 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Noroute\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#36 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#38 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#39 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#40 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#44 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#45 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#46 /var/www/kalimbatorium/data/www/kalimbatorium.ru/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#47 {main}

Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'store_ids' in 'where clause'
#0 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#5 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#6 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT COUNT(*)...', Array)
#7 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Data/Collection/AbstractDb.php(220): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#9 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(131): Magento\Framework\Data\Collection\AbstractDb->getSize()
#10 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(76): Mageplaza\Blog\Block\Post\Relatedpost->setTabTitle()
#11 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Mageplaza\Blog\Block\Post\Relatedpost->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Registry), Object(Mageplaza\Blog\Helper\Data), Array)
#12 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mageplaza\\Blog\\...', Array)
#13 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Blog\\...', Array)
#14 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Mageplaza\\Blog\\...', Array)
#15 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Mageplaza\\Blog\\...', Array)
#16 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Mageplaza\\Blog\\...', Array)
#17 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('Mageplaza\\Blog\\...', 'related.post.ta...', Array)
#18 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'related.post.ta...')
#19 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#21 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#22 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#23 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#24 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#25 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(254): Magento\Framework\View\Layout\Builder->build()
#26 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/View/Layout.php(875): Magento\Framework\View\Layout->build()
#27 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/View/Layout/Interceptor.php(414): Magento\Framework\View\Layout->getBlock('page_content_he...')
#28 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-cms/Helper/Page.php(171): Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#29 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-cms/Controller/Noroute/Index.php(44): Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Noroute\Index\Interceptor), 'no-route-2')
#30 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(24): Magento\Cms\Controller\Noroute\Index->execute()
#31 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Action/Action.php(107): Magento\Cms\Controller\Noroute\Index\Interceptor->execute()
#32 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Controller\Noroute\Index\Interceptor->___callParent('dispatch', Array)
#34 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Cms\Controller\Noroute\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Cms/Controller/Noroute/Index/Interceptor.php(39): Magento\Cms\Controller\Noroute\Index\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/FrontController.php(55): Magento\Cms\Controller\Noroute\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#42 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /var/www/kalimbatorium/data/www/kalimbatorium.ru/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, NULL)
#45 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /var/www/kalimbatorium/data/www/kalimbatorium.ru/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#47 /var/www/kalimbatorium/data/www/kalimbatorium.ru/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#48 {main}
```

Switching to production helped, all worked. Switching back to developer (I want to translate inline) resulting in dead site again.

**Comment by aholovan** [comment]
Hi ferret-e,

I got the same after update. That's because extension maintainer has not implemented correct update scripts yet. Currently 'store_ids' are in install script only. I decided do not spend time on that and just removed all blog's db tables, module version from Magento and installed it again. Fortunatelly I had not important data but if module on your store was already in use you can lost data, be careful! Also you can alter relevant tables manually: `store_ids` text NOT NULL COMMENT 'Store Id'
