### ISSUE TITLE
Syntax error or access violation

### ISSUE THREAD

**Issue by Nazzas** [mageplaza/magento-2-blog#106]
Hello,

In any product page, I'm have a SQL syntax error:

```
2 exception(s):
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2017-11-30 16:23:00')
Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table`
 INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1', `store_ids`)))) AND (`publish_date` <= '2017-11-30 16:23:00')
#0 /httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT COUNT(*)...', Array)
#6 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 /httpdocs/vendor/magento/framework/Data/Collection/AbstractDb.php(220): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#8 /httpdocs/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(131): Magento\Framework\Data\Collection\AbstractDb->getSize()
#9 /httpdocs/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(76): Mageplaza\Blog\Block\Post\Relatedpost->setTabTitle()
#10 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Mageplaza\Blog\Block\Post\Relatedpost->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Registry), Object(Mageplaza\Blog\Helper\Data), Array)
#11 /httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mageplaza\\Blog\\...', Array)
#12 /httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Blog\\...', Array)
#13 /httpdocs/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Mageplaza\\Blog\\...', Array)
#14 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Mageplaza\\Blog\\...', Array)
#15 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Mageplaza\\Blog\\...', Array)
#16 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('Mageplaza\\Blog\\...', 'related.post.ta...', Array)
#17 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'related.post.ta...')
#18 /httpdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#19 /httpdocs/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#21 /httpdocs/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#22 /httpdocs/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#23 /httpdocs/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#24 /httpdocs/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#25 /httpdocs/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#26 /httpdocs/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#27 /httpdocs/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#28 /httpdocs/vendor/magento/module-page-cache/Controller/Block.php(66): Magento\Framework\App\View->loadLayout(Array, true, true, false)
#29 /httpdocs/vendor/magento/module-page-cache/Controller/Block/Render.php(39): Magento\PageCache\Controller\Block->_getBlocks()
#30 /httpdocs/generated/code/Magento/PageCache/Controller/Block/Render/Interceptor.php(24): Magento\PageCache\Controller\Block\Render->execute()
#31 /httpdocs/vendor/magento/framework/App/Action/Action.php(107): Magento\PageCache\Controller\Block\Render\Interceptor->execute()
#32 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#33 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageCache\Controller\Block\Render\Interceptor->___callParent('dispatch', Array)
#34 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Controller\Block\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#35 /httpdocs/generated/code/Magento/PageCache/Controller/Block/Render/Interceptor.php(39): Magento\PageCache\Controller\Block\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /httpdocs/vendor/magento/framework/App/FrontController.php(55): Magento\PageCache\Controller\Block\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#40 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#41 /httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#42 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#45 /httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#46 /httpdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#47 /httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#48 {main}

Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('1',' at line 2
#0 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /httpdocs/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#2 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#3 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#5 /httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(517): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#6 /httpdocs/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(580): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('SELECT COUNT(*)...', Array)
#7 /httpdocs/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(828): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#8 /httpdocs/vendor/magento/framework/Data/Collection/AbstractDb.php(220): Zend_Db_Adapter_Abstract->fetchOne(Object(Magento\Framework\DB\Select), Array)
#9 /httpdocs/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(131): Magento\Framework\Data\Collection\AbstractDb->getSize()
#10 /httpdocs/vendor/mageplaza/magento-2-blog-extension/Block/Post/Relatedpost.php(76): Mageplaza\Blog\Block\Post\Relatedpost->setTabTitle()
#11 /httpdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Mageplaza\Blog\Block\Post\Relatedpost->__construct(Object(Magento\Framework\View\Element\Template\Context), Object(Magento\Framework\Registry), Object(Mageplaza\Blog\Helper\Data), Array)
#12 /httpdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Mageplaza\\Blog\\...', Array)
#13 /httpdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Mageplaza\\Blog\\...', Array)
#14 /httpdocs/vendor/magento/framework/View/Element/BlockFactory.php(45): Magento\Framework\ObjectManager\ObjectManager->create('Mageplaza\\Blog\\...', Array)
#15 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(269): Magento\Framework\View\Element\BlockFactory->createBlock('Mageplaza\\Blog\\...', Array)
#16 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(249): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Mageplaza\\Blog\\...', Array)
#17 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(227): Magento\Framework\View\Layout\Generator\Block->createBlock('Mageplaza\\Blog\\...', 'related.post.ta...', Array)
#18 /httpdocs/vendor/magento/framework/View/Layout/Generator/Block.php(135): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'related.post.ta...')
#19 /httpdocs/vendor/magento/framework/View/Layout/GeneratorPool.php(80): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#20 /httpdocs/vendor/magento/framework/View/Layout.php(344): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#21 /httpdocs/generated/code/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#22 /httpdocs/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#23 /httpdocs/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#24 /httpdocs/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#25 /httpdocs/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#26 /httpdocs/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#27 /httpdocs/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#28 /httpdocs/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#29 /httpdocs/vendor/magento/module-page-cache/Controller/Block.php(66): Magento\Framework\App\View->loadLayout(Array, true, true, false)
#30 /httpdocs/vendor/magento/module-page-cache/Controller/Block/Render.php(39): Magento\PageCache\Controller\Block->_getBlocks()
#31 /httpdocs/generated/code/Magento/PageCache/Controller/Block/Render/Interceptor.php(24): Magento\PageCache\Controller\Block\Render->execute()
#32 /httpdocs/vendor/magento/framework/App/Action/Action.php(107): Magento\PageCache\Controller\Block\Render\Interceptor->execute()
#33 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\PageCache\Controller\Block\Render\Interceptor->___callParent('dispatch', Array)
#35 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\PageCache\Controller\Block\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#36 /httpdocs/generated/code/Magento/PageCache/Controller/Block/Render/Interceptor.php(39): Magento\PageCache\Controller\Block\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#37 /httpdocs/vendor/magento/framework/App/FrontController.php(55): Magento\PageCache\Controller\Block\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#39 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#40 /httpdocs/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /httpdocs/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#43 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#44 /httpdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#45 /httpdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#46 /httpdocs/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#47 /httpdocs/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#48 /httpdocs/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#49 {main}
```
The link is something like: /page_cache/block/render/id/4375/...

I'm in dev mode, magento setup:upgrade, cache flushed and cleared.

**Comment by Tuvpt** [comment]
I'm Curtis from Mageplaza.
Regarding your reported issue, I can answer as below:
in Mageplaza\Blog\Block\Post\Relatedpost, you should check function getRelatedPostList() in the following form:

    public function getRelatedPostList()
    {
        if ($this->_relatedPosts == null) {
            /** @var \Mageplaza\Blog\Model\ResourceModel\Post\Collection $collection */
            $collection = $this->helperData->getPostList();
            $collection->getSelect()
                ->join([
                    'related' => $collection->getTable('mageplaza_blog_post_product')],
                    'related.post_id=main_table.post_id AND related.entity_id=' . $this->getProductId()
                )
                ->limit($this->getLimitPosts());

            $this->_relatedPosts = $collection;
        }

        return $this->_relatedPosts;
    }

If there are any further problems, feel free to contact us.
Thank you!

**Comment by baljinderimpinge** [comment]
Hello,

In any product page, I'm have a SQL syntax error:

2 exception(s): Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('4',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table` INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('4', `store_ids`)))) AND (`publish_date` <= '2019-12-27 09:59:13') Exception #1 (PDOException): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('4',' at line 2 Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('4',' at line 2, query was: SELECT COUNT(*) FROM `mageplaza_blog_post` AS `main_table` INNER JOIN `mageplaza_blog_post_product` AS `related` ON related.post_id=main_table.post_id AND related.entity_id= WHERE (`enabled` = '1') AND (((FIND_IN_SET(0, `store_ids`)) OR (FIND_IN_SET('4', `store_ids`)))) AND (`publish_date` <= '2019-12-27 09:59:13') #0 /home/cloudpanel/htdocs/test.shisha-koenig.ch/vendor/magento/framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array) #1
