### ISSUE TITLE
Can't add new post

### ISSUE THREAD

**Issue by Pekkonen** [mageplaza/magento-2-blog#155]
1. Magento: 2.2.7
2. PHP: 7.0.32
3. MySQL: 5.6.42

### Steps to reproduce
1. Install from  via composer.
2. Just click to "Add new post" button
3. Fill "Name", "Short Description", "Content", etc
4. Click "Save" button
5. See an error in admin:
"Something went wrong while saving the Post.
This post no longer exists."
And no post in list.

I tried to add category and topic to post, but no successfully too.

What's wrong and why I see this exception?

**Comment by ChienNguyenVP** [comment]
Hi, 
I tried to install the latest Blog extension with Magento 2.2.7. But I did not have a problem.
Please try again. If you still have an error. Don't worry, please contact me at https://mageplaza.freshdesk.com/support/home
I will continue to solve the problem for you.
Thank you!

**Comment by Pekkonen** [comment]
Hi!
Thanks for your response!
Unfortunately error still exist.
I uninstall your extension (initial installed via composer) and installed
again manually as described in
https://www.mageplaza.com/install-magento-2-extension/ in section "Solution
#1: Ready to paste"
But I see same an error and can't create post.


чт, 6 дек. 2018 г. в 11:40, Nguyễn Minh Chiến <notifications@github.com>:

**Comment by ChienNguyenVP** [comment]
Hi,
Please contact us at https://mageplaza.freshdesk.com/support/home.
Our specialists will help you.
Thank you!

**Comment by Sade** [comment]
Magento: 2.2.6
PHP: 7.1.23
MySQL: 5.7
Locale: fr_FR

it seem to be an accentued char issue.

My debug log : 
```ApacheConf
[2018-12-12 14:38:57] main.CRITICAL: Exception message: DateTime::__construct(): Failed to parse time string (12 déc. 2018 14:38:57) at position 0 (1): Unexpected character
Trace:
#0 ...\vendor\magento\framework\Stdlib\DateTime.php(57): DateTime->__construct('12 d\xC3\xA9c. 2018 1...')
#1 ...\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(2802): Magento\Framework\Stdlib\DateTime->formatDate(Object(Zend_Date), true)
#2 ...\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(3030): Magento\Framework\DB\Adapter\Pdo\Mysql->formatDate(Object(Zend_Date))
#3 ...\vendor\magento\framework\Model\ResourceModel\AbstractResource.php(183): Magento\Framework\DB\Adapter\Pdo\Mysql->prepareColumnValue(Array, Object(Zend_Date))
#4 ...\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(541): Magento\Framework\Model\ResourceModel\AbstractResource->_prepareDataForTable(Object(Mageplaza\Blog\Model\Author), 'mageplaza_blog_...')
#5 ...\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(817): Magento\Framework\Model\ResourceModel\Db\AbstractDb->_prepareDataForSave(Object(Mageplaza\Blog\Model\Author))
#6 ...\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(413): Magento\Framework\Model\ResourceModel\Db\AbstractDb->updateObject(Object(Mageplaza\Blog\Model\Author))
#7 ...\vendor\magento\framework\Model\AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Author))
#8 ...\vendor\mageplaza\magento-2-blog-extension\Model\ResourceModel\Post.php(510): Magento\Framework\Model\AbstractModel->save()
#9 ...\vendor\mageplaza\magento-2-blog-extension\Model\ResourceModel\Post.php(181): Mageplaza\Blog\Model\ResourceModel\Post->saveAuthor()
#10 ...\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(831): Mageplaza\Blog\Model\ResourceModel\Post->_afterSave(Object(Mageplaza\Blog\Model\Post))
#11 ...\vendor\magento\framework\Model\ResourceModel\Db\AbstractDb.php(418): Magento\Framework\Model\ResourceModel\Db\AbstractDb->processAfterSaves(Object(Mageplaza\Blog\Model\Post))
#12 ...\vendor\magento\framework\Model\AbstractModel.php(647): Magento\Framework\Model\ResourceModel\Db\AbstractDb->save(Object(Mageplaza\Blog\Model\Post))
#13 ...\vendor\mageplaza\magento-2-blog-extension\Controller\Adminhtml\Post\Save.php(97): Magento\Framework\Model\AbstractModel->save()
#14 ...\generated\code\Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor.php(24): Mageplaza\Blog\Controller\Adminhtml\Post\Save->execute()
#15 ...\vendor\magento\framework\App\Action\Action.php(107): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->execute()
#16 ...\vendor\magento\module-backend\App\AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#17 ...\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#18 ...\vendor\magento\framework\Interception\Interceptor.php(138): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callParent('dispatch', Array)
#19 ...\vendor\magento\module-backend\App\Action\Plugin\Authentication.php(143): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 ...\vendor\magento\framework\Interception\Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#21 ...\vendor\magento\framework\Interception\Interceptor.php(153): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#22 ...\generated\code\Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor.php(39): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->___callPlugins('dispatch', Array, NULL)
#23 ...\vendor\magento\framework\App\FrontController.php(55): Mageplaza\Blog\Controller\Adminhtml\Post\Save\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#24 ...\vendor\magento\framework\Interception\Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#25 ...\vendor\magento\framework\Interception\Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#26 ...\vendor\magento\framework\Interception\Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#27 ...\generated\code\Magento\Framework\App\FrontController\Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#28 ...\vendor\magento\framework\App\Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#29 ...\generated\code\Magento\Framework\App\Http\Interceptor.php(24): Magento\Framework\App\Http->launch()
#30 ...\vendor\magento\framework\App\Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()
#31 ...\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#32 {main} [] []```

**Comment by BigTonni** [comment]
Hi!

Magento: 2.2.6
PHP: 7.0.33
MySQL: 5.7.24

Install from via composer.
Mageplaza_Core - version 1.4.1
Mageplaza_Core - version 3.0.3
Click to "Add new post" button. Fill all fields. Click "Save" button
See an error in admin:
"Something went wrong while saving the Post.
This post no longer exists."

http://joxi.ru/krD8BYnIKKK6Br

And no post in list.
Category,  topic and tag created successfully too.

What's wrong and why I see this exception?

**Comment by ChienNguyenVP** [comment]
Hi,
I think you should try installing the blog extension again. 
Then add new posts and let me know the results.
If the error still occurs, I will continue to help you.
Thank you!

**Comment by BigTonni** [comment]
Hi @ChienNguyenVP ,

After command:
composer update mageplaza/magento-2-blog-extension
Info from console:
"Nothing to install or update
Generating autoload files"

My commands:
php bin/magento module:disable Mageplaza_Blog
php bin/magento module:enable Mageplaza_Blog
php bin/magento setup:upgrade
php bin/magento setup:static-content:deploy -f

Add new post and I see old errors:
"Something went wrong while saving the Post.
This post no longer exists."

What other solutions do you have?

**Comment by BigTonni** [comment]
Thank you! I wrote a ticket there.
