### ISSUE TITLE
API rest issue

### ISSUE THREAD

**Issue by JDavidVR** [mageplaza/magento-2-blog#270]
Module has API REST issues when trying to di any REST call

### Preconditions
1. Magento: Opensource 2.3.4
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce
1. Install module using composer
2.  Open Api rest URL: http://your.magento.site/rest/all/schema?services=all 

### Expected result

1. All endpoints are listed correctly

### Actual result
```
<response>
<message>The "PostInterface" class doesn't exist and the namespace must be specified. Verify and try again.</message>
<trace>#0 /home/m/m234/vendor/magento/module-webapi/Model/Config/ClassReflector.php(103): Magento\Framework\Reflection\TypeProcessor->register('PostInterface') #1 /home/m/m234/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection)) #2 /home/m/m234/vendor/magento/module-webapi/Model/ServiceMetadata.php(133): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('Mirasvit\\Blog\\A...', Array) #3 /home/m/m234/vendor/magento/module-webapi/Model/ServiceMetadata.php(166): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata() #4 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Model\ServiceMetadata->getServicesConfig() #5 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callParent('getServicesConf...', Array) #6 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Model\ServiceMetadata\Interceptor->Magento\Framework\Interception\{closure}() #7 /home/m/m234/generated/code/Magento/Webapi/Model/ServiceMetadata/Interceptor.php(26): Magento\Webapi\Model\ServiceMetadata\Interceptor->___callPlugins('getServicesConf...', Array, Array) #8 /home/m/m234/vendor/magento/module-webapi/Model/Rest/Swagger/Generator.php(969): Magento\Webapi\Model\ServiceMetadata\Interceptor->getServicesConfig() #9 /home/m/m234/vendor/magento/module-webapi/Controller/Rest/SchemaRequestProcessor.php(53): Magento\Webapi\Model\Rest\Swagger\Generator->getListOfServices() #10 /home/m/m234/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SchemaRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy)) #11 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http)) #12 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array) #13 /home/m/m234/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http)) #14 /home/m/m234/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array) #15 /home/m/m234/vendor/magento/framework/App/Http.php(137): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) #16 /home/m/m234/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch() #17 /home/m/m234/vendor/magento/framework/App/Bootstrap.php(261): Magento\Framework\App\Http\Interceptor->launch() #18 /home/m/m234/index.php(38): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor)) #19 {main}</trace>
</response>
```

**Comment by Bang512** [comment]
Hi @JDavidVR,

Thanks for contacting us.
I have already received your issue report.
I am checking your problem and I will reply to you soon.

Thanks!
