### ISSUE TITLE
When admin click content ->mageplaza blog->category  getting error

### ISSUE THREAD

**Issue by saurabh20394** [mageplaza/magento-2-blog#275]
Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/Data/Tree/Dbp.php:380 Stack trace: #0 /var/www/html/demo30.laraveldevloper.in/vendor/magento/module-catalog/Block/Adminhtml/Category/AbstractCategory.php(157): Magento\Framework\Data\Tree\Dbp->loadEnsuredNodes(Object(Mageplaza\Blog\Model\Category), NULL) #1 /var/www/html/demo30.laraveldevloper.in/vendor/magento/module-catalog/view/adminhtml/templates/catalog/category/tree.phtml(11): Magento\Catalog\Block\Adminhtml\Category\AbstractCategory->getRoot() #2 /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/d...') #3 /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Blog\Block\Adminhtml\Category\Tree), '/var/www/html/d...', Array) #4 /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/View/Elemen in /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/Data/Tree/Dbp.php on line 380

**Comment by saurabh20394** [comment]
Fatal error: Uncaught Error: Call to a member function getStoreIds() on null in /var/www/html/demo30.laraveldevloper.in/app/code/Mageplaza/Blog/Block/Adminhtml/Category/Tree.php:159 Stack trace: #0 /var/www/html/demo30.laraveldevloper.in/vendor/magento/module-catalog/Block/Adminhtml/Category/Tree.php(301): Mageplaza\Blog\Block\Adminhtml\Category\Tree->_getNodeJson(NULL) #1 /var/www/html/demo30.laraveldevloper.in/app/code/Mageplaza/Blog/Block/Adminhtml/Category/Tree.php(139): Magento\Catalog\Block\Adminhtml\Category\Tree->getTree(NULL) #2 /var/www/html/demo30.laraveldevloper.in/app/code/Mageplaza/Blog/Block/Category/Widget.php(44): Mageplaza\Blog\Block\Adminhtml\Category\Tree->getTree(NULL, '1') #3 /var/www/html/demo30.laraveldevloper.in/app/code/Mageplaza/Blog/view/frontend/templates/category/widget.phtml(22): Mageplaza\Blog\Block\Category\Widget->getTree() #4 /var/www/html/demo30.laraveldevloper.in/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/d...') #5 /var/www/html/demo30.laraveldevlo in /var/www/html/demo30.laraveldevloper.in/app/code/Mageplaza/Blog/Block/Adminhtml/Category/Tree.php on line 159

**Comment by asifsomy** [comment]
Did you find a fix? I have same problem on Magento 2.3.5-p1


atal error: Uncaught Error: Call to a member function getStoreIds() on null in .../app/code/Mageplaza/Blog/Block/Adminhtml/Category/Tree.php:159 Stack trace: #0

**Comment by giaphn** [comment]
Hi, 
I'm Shox from Mageplaza.
This problem occurs because you doesn't have root category in mageplaza_blog_table: https://prnt.sc/tnqn4b.
Please add root category in your db and check again.

**Comment by ManishaVasani** [comment]
Hi @giaphn ,

I am facing same issue in Mageplaza_Blog version : 3.1.3
Magento Version: Magento ver. 2.3.5-p1

Steps to reproduce
Go to admin area
Open Content -> Better Blog -> Categories

Error :
Fatal error: Uncaught Error: Call to a member function getId() on null in /var/www/html/nuttydelights/vendor/magento/framework/Data/Tree/Dbp.php:380

Can you please provide example for add root category in db,

Thanks,
Manisha

**Comment by ManishaVasani** [comment]
Hi @asifsomy ,

Please try this solution of Bang512 , it's working for me : 
https://github.com/mageplaza/magento-2-blog/issues/271
and set category_id : 1

**Comment by mikamarkus** [comment]
Hi,

I faced the same issue in Magento 2.4.1 Cloud Environment. Root category_id in mageplaza_blog_category table was 2.

I just updated it with SQL command.

`UPDATE mageplaza_blog_category SET category_id = 1 WHERE category_id = 2;`
